### PR TITLE
Add python script that tests notebooks.

### PR DESCRIPTION
**Pull request by grebe**
Address #32.

The test has a list of expected errors. The script runs each notebook and checks that it has the expected number of errors, and that each error contains a given substring.

### CODE REVIEW

**Comment by edwardcwang** [comment]
Nice! 💯

Two thoughts:

1) It seems to take quite long to run (>6 minutes and it didn't even finish (see below). I think we should add a flag to allow us to only run it for certain notebooks since it does take a while to run.

(e.g. this is what the Python3 language unit tests have - since it takes a while to run the entire test suite, it provides an option to only run parts of the test suite corresponding to the code you are actively working on.)

2) It seems to fail at module 3.3 for me for whatever reason...

```
[NbConvertApp] Converting notebook 3.3_higher-order_functions.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: scala
[NbConvertApp] Writing 26512 bytes to /tmp/tmps3sx34x5.ipynb
3
5
Traceback (most recent call last):
  File "./runtest.py", line 69, in <module>
    check_errors(expected, errors)
  File "./runtest.py", line 35, in check_errors
    assert len(expected) == len(actual)
AssertionError
```

**Comment by grebe** [comment]
Re: 1, is there a canonical examples for this?

Re: 2, the test might be broken. I was getting timeouts on my current machine so I just pushed hoping that I had gotten it right earlier. It prints out the expected and actual number of errors, so the mismatch means I didn't collect all the errors.

Also, not sure if I'm going crazy, but I think I remembered seeing the number of errors vary from run to run. Keep an eye out for that.

**Comment by edwardcwang** [comment]
1) Just pushed a commit that implements something like that

2) It seems to be slow and failing on my machine (just ran it again):

```
[NbConvertApp] Converting notebook 3.3_higher-order_functions.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: scala
[NbConvertApp] Writing 26512 bytes to /tmp/tmpywwuu19s.ipynb
3
5
Traceback (most recent call last):
  File "./runtest.py", line 82, in <module>
    check_errors(expected, errors)
  File "./runtest.py", line 38, in check_errors
    assert len(expected) == len(actual)
AssertionError
```

**Comment by grebe** [comment]
Working on fixes for the actual tests, it's just slow to run.

**Pull request merged**
