### PR TITLE
Attempted binder fix

### PR DESCRIPTION
**Pull request by edwardcwang**
Worth a try? The setup works fine for me locally.

### CODE REVIEW

**Comment by ucbjrl** [comment]
To test this, you'll need to blow away your `ivy` and `coursier` caches to emulate the downloading that will happen on a newly created VM/docker instance.

**Comment by edwardcwang** [comment]
Just tried with both caches emptied out and it still seems to work. Let's give this a shot.

**Comment by ucbjrl** [comment]
Now I get:
```
Your session is taking longer than usual to start!
Check the log messages below to see what is happening.
```
and the Build logs ends with:
```
Wrote /home/jovyan/almond
Installed scala kernel under /home/jovyan/.local/share/jupyter/kernels/scala
Building jupyterlab assets (build:prod:minimize)
/
```
the last line of which was a spinning sequence which is no longer spinning.

A subsequent attempt to reload the page produces:
```
Found built image, launching...
Launching server...
```
followed by
```
Your session is taking longer than usual to start!
Check the log messages below to see what is happening.
```
It seems to me that mybinder.org's image management has problems.

**Comment by edwardcwang** [comment]
Is it time to raise an issue with Binder then?

**Pull request merged**
